defaults: &defaults
  docker:
    - image: circleci/node:7.10
  working_directory: ~/superGobang
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    <<: *defaults
    - attach_workspace:
      at: ~/superGobang
    steps:
      - checkout
      - run: yarn test

all_tags: &all_tags
  filters:
    branches:
      only: master
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
        <<: *all_tags
      - test:
        <<: *all_tags
        requires:
          - build
