defaults: &defaults
  working_directory: /tmp/superGobang
  docker:
    - image: circleci/node:7.10
restore_repo: &restore_repo
  restore_cache:
    keys:
      - v1-dependencies-{{ .Branch }}-{{ .Revision }}
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - *restore_repo
      - checkout
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ .Branch }}-{{ .Revision }}
  test:
    <<: *defaults
    steps:
      - *restore_repo
      - checkout
      - attach_workspace:
          at: ~/superGobang
      - run: yarn test

all_tags: &all_tags
  filters:
    branches:
      only: master
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          <<: *all_tags
      - test:
          <<: *all_tags
          requires:
            - build
