defaults: &defaults
  working_directory: /tmp/super-gobang
  docker:
    - image: circleci/node:7.10
restore_repo: &restore_repo
  restore_cache:
    keys:
      - v1-dependencies-{{ .Branch }}-{{ .Revision }}
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - *restore_repo
      - checkout
      - run: yarn install
      - save_cache:
          paths:
            - /tmp/super-gobang
          key: v1-dependencies-{{ .Branch }}-{{ .Revision }}
  test:
    <<: *defaults
    steps:
      - *restore_repo
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      - run: yarn test

all_tags: &all_tags
  filters:
    branches:
      only: master
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          <<: *all_tags
      - test:
          <<: *all_tags
          requires:
            - build
